# name: "sandbox"
# version: "1.0.0"
# config-version: 2

# profile: "default"

# model-paths: ["models"]
# analysis-paths: ["analyses"]
# test-paths: ["tests"]
# seed-paths: ["seeds"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

# target-path: "target"
# clean-targets:
#   - "target"
#   - "dbt_packages"

# models:
#   sandbox:
#     example:
#       +materialized: table


name: dbtvault_snowflake_demo
version: '1.0.0'
# require-dbt-version: ['>=0.18.0', '<0.19.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - seeds
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: '1992-01-08'
  tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  dbtvault_snowflake_demo:
    raw_stage:
      tags:
        - 'raw'
      materialized: view
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'
